### ISSUE TITLE
Change name to Boilerplate Lib to avoid confusion?

### ISSUE THREAD

**Issue by ProfessorProspector** [BrassGoggledCoders/Boilerplate#11]
I think it'll be better that way to make it clear it is a library and not a content mod.

**Comment by decebaldecebal** [comment]
Makes sense to me +1

**Comment by warlordjones** [comment]
Could do - maybe Boilerplate Library for github etc and then obviously Lib for short.

**Comment by warlordjones** [comment]
Will be done as we move to 1.8.9 - public facing names only, will remain as boilerplate within code.

**Comment by SkySom** [comment]
So eh... Since I actually changed Boilerplate to be shaded... BoilerplateLib.Lib doesn't make too much sense. Most probably won't have to see it in 1.8.9, so I feel this is somewhat moot. Gonna close unless someone has real problem with leaving as is...

**Comment by ProfessorProspector** [comment]
Yeah it's not really necessary.
