### ISSUE TITLE
ClassCastException when skeleton shoots

### ISSUE THREAD

**Issue by LlubNek** [BrassGoggledCoders/Boilerplate#12]
So, this happened (didn't see the skeleton or the arrow):
```
[03:15:06] [Client thread/ERROR]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingAttackEvent@3cf9990a:
java.lang.ClassCastException: net.minecraft.entity.projectile.EntityTippedArrow cannot be cast to net.minecraft.entity.EntityLivingBase
	at xyz.brassgoggledcoders.modularutilities.modules.enchantments.EnchantmentsModule.onEntityAttacked(EnchantmentsModule.java:126) ~[EnchantmentsModule.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_600_EnchantmentsModule_onEntityAttacked_LivingAttackEvent.invoke(.dynamic) ~[?:?]
```

I'm using Boilerplate-1.9.4-8.2.2.jar with Forge 12.18.0.2007 and LiteLoader snapshot on Minecraft 1.10.2.

Here's the log:
[latest.log.1.txt](https://github.com/BrassGoggledCoders/Boilerplate/files/347224/latest.log.1.txt)

Here's the crash report:
[crash-2016-07-05_03.15.11-server.txt](https://github.com/BrassGoggledCoders/Boilerplate/files/347231/crash-2016-07-05_03.15.11-server.txt)

This happened in version 8.2.1 too (skeleton was right in front of me, could see arrow in flight as minecraft crashed):
log:  [latest.log.txt](https://github.com/BrassGoggledCoders/Boilerplate/files/347235/latest.log.txt)

crash report:  [crash-2016-07-05_02.37.00-server.txt](https://github.com/BrassGoggledCoders/Boilerplate/files/347236/crash-2016-07-05_02.37.00-server.txt)

In version 8.2.2 there was also a weird message the first time I tried to enter the world before booting me back to the server select screen and Windows Firewall popped up asking me to make an exception for java.  This is rather odd since I was playing singleplayer.  You might want to review whatever changes you just made between 8.2.1 and 8.2.2.

**Comment by warlordjones** [comment]
This is actually a ModularUtilities issue. Fixed release coming this afternoon.

There shouldn't be changes between 8.2.1/8.2.2 to cause that o.O

**Comment by warlordjones** [comment]
Should be fixed in latest versions of boilerplate and modular utilities?
